"""Backtesting engine for intraday momentum strategies.

Simulates portfolio execution based on strategy signals, tracks
equity curve, and computes trade-level statistics.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from ..strategies.base import BaseStrategy, Signal

logger = logging.getLogger(__name__)


@dataclass
class Trade:
    """Record of a single round-trip trade.

    Attributes
    ----------
    entry_time : pd.Timestamp
        Time of entry signal.
    exit_time : pd.Timestamp
        Time of exit signal.
    direction : int
        ``1`` for long, ``-1`` for short.
    entry_price : float
        Price at entry.
    exit_price : float
        Price at exit.
    leverage : float
        Leverage used.
    pnl : float
        Profit/loss in dollars.
    return_pct : float
        Return as a percentage.
    """

    entry_time: pd.Timestamp
    exit_time: pd.Timestamp
    direction: int
    entry_price: float
    exit_price: float
    leverage: float
    pnl: float = 0.0
    return_pct: float = 0.0


@dataclass
class BacktestResult:
    """Container for backtesting results.

    Attributes
    ----------
    equity_curve : pd.Series
        Time series of portfolio value.
    trades : list[Trade]
        List of completed trades.
    signals : list[Signal]
        All signals generated by the strategy.
    initial_capital : float
        Starting capital.
    final_equity : float
        Ending portfolio value.
    """

    equity_curve: pd.Series
    trades: list[Trade] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    initial_capital: float = 100_000.0
    final_equity: float = 0.0

    @property
    def total_return(self) -> float:
        """Total return as a percentage."""
        return (self.final_equity / self.initial_capital - 1) * 100

    @property
    def num_trades(self) -> int:
        """Number of completed round-trip trades."""
        return len(self.trades)

    @property
    def win_rate(self) -> float:
        """Fraction of profitable trades."""
        if not self.trades:
            return 0.0
        wins = sum(1 for t in self.trades if t.pnl > 0)
        return wins / len(self.trades)

    def summary(self) -> dict[str, float]:
        """Return a summary dictionary of key metrics.

        Returns
        -------
        dict[str, float]
            Dictionary with performance metrics.
        """
        returns = self.equity_curve.pct_change().dropna()
        sharpe = 0.0
        if len(returns) > 1 and returns.std() > 0:
            sharpe = returns.mean() / returns.std() * np.sqrt(252 * 390)  # annualized

        max_dd = 0.0
        if len(self.equity_curve) > 0:
            peak = self.equity_curve.expanding().max()
            drawdown = (self.equity_curve - peak) / peak
            max_dd = drawdown.min() * 100

        avg_win = 0.0
        avg_loss = 0.0
        wins = [t.return_pct for t in self.trades if t.pnl > 0]
        losses = [t.return_pct for t in self.trades if t.pnl <= 0]
        if wins:
            avg_win = np.mean(wins)
        if losses:
            avg_loss = np.mean(losses)

        return {
            "initial_capital": self.initial_capital,
            "final_equity": self.final_equity,
            "total_return_pct": self.total_return,
            "num_trades": self.num_trades,
            "win_rate": self.win_rate,
            "avg_win_pct": avg_win,
            "avg_loss_pct": avg_loss,
            "sharpe_ratio": sharpe,
            "max_drawdown_pct": max_dd,
        }


class BacktestEngine:
    """Execute a strategy on historical data and produce results.

    Parameters
    ----------
    initial_capital : float
        Starting portfolio value.
    commission_per_share : float
        Commission cost per share traded.

    Examples
    --------
    >>> engine = BacktestEngine(initial_capital=100_000)
    >>> result = engine.run(strategy, daily_data, minute_data)
    >>> print(result.summary())
    """

    def __init__(
        self,
        initial_capital: float = 100_000.0,
        commission_per_share: float = 0.005,
    ) -> None:
        self.initial_capital = initial_capital
        self.commission_per_share = commission_per_share

    def run(
        self,
        strategy: BaseStrategy,
        daily_data: pd.DataFrame,
        minute_data: pd.DataFrame,
    ) -> BacktestResult:
        """Run a full backtest.

        Parameters
        ----------
        strategy : BaseStrategy
            Strategy instance to evaluate.
        daily_data : pd.DataFrame
            Daily OHLCV data.
        minute_data : pd.DataFrame
            Minute-bar OHLCV data.

        Returns
        -------
        BacktestResult
            Complete backtest results with equity curve and trades.
        """
        signals = strategy.generate_signals(daily_data, minute_data)
        logger.info("Generated %d signals", len(signals))

        equity = self.initial_capital
        equity_points: list[tuple[pd.Timestamp, float]] = []
        trades: list[Trade] = []

        position = 0
        entry_price = 0.0
        entry_time: pd.Timestamp | None = None
        entry_leverage = 0.0

        for signal in signals:
            price = minute_data.loc[signal.timestamp, "Close"]
            if isinstance(price, pd.Series):
                price = price.iloc[0]

            if signal.direction != 0 and position == 0:
                # Open position
                position = signal.direction
                entry_price = price
                entry_time = signal.timestamp
                entry_leverage = signal.leverage

            elif signal.direction == 0 and position != 0:
                # Close position
                pnl = position * (price - entry_price) / entry_price * equity * entry_leverage
                # Subtract commissions
                shares = equity * entry_leverage / entry_price
                commission = abs(shares) * self.commission_per_share * 2
                pnl -= commission
                return_pct = pnl / equity * 100

                equity += pnl
                trades.append(
                    Trade(
                        entry_time=entry_time,
                        exit_time=signal.timestamp,
                        direction=position,
                        entry_price=entry_price,
                        exit_price=price,
                        leverage=entry_leverage,
                        pnl=pnl,
                        return_pct=return_pct,
                    )
                )
                position = 0

            equity_points.append((signal.timestamp, equity))

        equity_curve = pd.Series(
            {ts: eq for ts, eq in equity_points},
            name="equity",
        )

        return BacktestResult(
            equity_curve=equity_curve,
            trades=trades,
            signals=signals,
            initial_capital=self.initial_capital,
            final_equity=equity,
        )
